enable-magisk-update = true
patches-source = "MorpheApp/morphe-patches"
rv-brand = "MorpheApp"
parallel-jobs = 1

[YouTube]
build-mode = "both"
excluded-patches = "Custom branding"
included-patches = "Material You"
patcher-args = " -e 'GmsCore support' -OpackageNameYouTube='yt.rv.morphe' "
version = "auto"
exclusive-patches = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rv-morphe"

[Music]
arch = "both"
build-mode = "both"
app-name = "YT Music"
excluded-patches = "Custom branding"
included-patches = "Material You"
patcher-args = " -e 'GmsCore support' -OpackageNameYouTubeMusic='ytm.rv.morphe' "
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rv-morphe"
